export interface NavItem {
    title: string;
    slug: string;
}

export interface NavSection {
    title: string;
    items: NavItem[];
}

export const navigation: NavSection[] = [
    {
        title: "Bubble Tea",
        items: [
            { title: "Introduction", slug: "bubbletea/introduction" },
            { title: "The Model", slug: "bubbletea/the-model" },
            { title: "Messages & Commands", slug: "bubbletea/messages-and-commands" },
            { title: "The Update Loop", slug: "bubbletea/the-update-loop" },
            { title: "The View", slug: "bubbletea/the-view" },
            { title: "Basic Example", slug: "bubbletea/example-basic" },
            { title: "Styled Example", slug: "bubbletea/example-styled" },
            { title: "Persistent Storage", slug: "bubbletea/example-persistent" },
            { title: "Enhanced Styling", slug: "bubbletea/example-enhanced" },
            { title: "Viewport Example", slug: "bubbletea/example-viewport" },
        ],
    },
    {
        title: "Go",
        items: [
            { title: "Getting Started", slug: "go/getting-started" },
            { title: "Variables & Constants", slug: "go/variables-and-constants" },
            { title: "Data Types & Pointers", slug: "go/data-types-and-pointers" },
            { title: "Zero Values", slug: "go/zero-values" },
            { title: "Arrays & Slices", slug: "go/arrays-and-slices" },
            { title: "Maps & Structs", slug: "go/maps-and-structs" },
            { title: "Loops & Conditionals", slug: "go/loops-and-conditionals" },
            { title: "Enums", slug: "go/enums" },
            { title: "Closures", slug: "go/closures" },
            { title: "Methods & Receivers", slug: "go/methods-and-receivers" },
            { title: "Interfaces", slug: "go/interfaces" },
            { title: "Type Switching", slug: "go/type-switching" },
            { title: "Type System", slug: "go/type-system" },
            { title: "Generics", slug: "go/generics" },
            { title: "Packages & Scope", slug: "go/packages-and-scope" },
            { title: "User Input", slug: "go/user-input" },
            { title: "File Handling", slug: "go/file-handling" },
            { title: "Standard Library", slug: "go/standard-library" },
            { title: "Concurrency", slug: "go/concurrency" },
            { title: "Channels", slug: "go/channels" },
            { title: "Mutex", slug: "go/mutex" },
            { title: "Go Idioms", slug: "go/go-idioms" },
        ],
    },
    {
        title: "Rust",
        items: [
            { title: "Getting Started", slug: "rust/getting-started" },
            { title: "Variables & Types", slug: "rust/variables-and-types" },
            { title: "Control Flow", slug: "rust/control-flow" },
            { title: "Functions & Macros", slug: "rust/functions-and-macros" },
            { title: "Arrays & Tuples", slug: "rust/arrays-and-tuples" },
            { title: "Strings", slug: "rust/strings" },
            { title: "References & Borrowing", slug: "rust/references-and-borrowing" },
            { title: "Structs", slug: "rust/structs" },
            { title: "Enums & Options", slug: "rust/enums-and-options" },
            { title: "Constants & Statics", slug: "rust/constants-and-statics" },
            { title: "Pattern Matching", slug: "rust/pattern-matching" },
            { title: "Methods & Impl", slug: "rust/methods-and-impl" },
            { title: "Traits", slug: "rust/traits" },
            { title: "Modules & Project Structure", slug: "rust/modules-and-project-structure" },
            { title: "Generics", slug: "rust/generics" },
            { title: "Trait Objects", slug: "rust/trait-objects" },
            { title: "Closures", slug: "rust/closures" },
            { title: "Ownership & Memory", slug: "rust/ownership-and-memory" },
            { title: "Smart Pointers", slug: "rust/smart-pointers" },
        ],
    },
    {
        title: "TypeScript",
        items: [
            { title: "Getting Started", slug: "typescript/getting-started" },
            { title: "Basic Types", slug: "typescript/basic-types" },
            { title: "Arrays & Tuples", slug: "typescript/arrays-and-tuples" },
            { title: "Enums", slug: "typescript/enums" },
            { title: "Functions & Modules", slug: "typescript/functions-and-modules" },
            { title: "Interfaces", slug: "typescript/interfaces" },
            { title: "Types vs Interfaces", slug: "typescript/types-vs-interfaces" },
            { title: "Union & Intersection Types", slug: "typescript/union-and-intersection-types" },
            { title: "Type Guards", slug: "typescript/type-guards" },
            { title: "Classes", slug: "typescript/classes" },
            { title: "Generics", slug: "typescript/generics" },
            { title: "Utility Types", slug: "typescript/utility-types" },
            { title: "Advanced Types", slug: "typescript/advanced-types" },
            { title: "Records & Maps", slug: "typescript/records-and-maps" },
            { title: "Zod & Validation", slug: "typescript/zod-and-validation" },
        ],
    },
    {
        title: "DevOps",
        items: [
            { title: "Git & GitHub", slug: "devops/git" },
            { title: "Docker", slug: "devops/docker" },
            { title: "CI/CD Pipelines", slug: "devops/ci-cd" },
        ],
    },
    {
        title: "DSA with C++",
        items: [
            { title: "Getting Started", slug: "dsa-cpp/getting-started" },
            { title: "STL Containers", slug: "dsa-cpp/stl-containers" },
            { title: "Associative Containers", slug: "dsa-cpp/stl-associative" },
            { title: "STL Algorithms", slug: "dsa-cpp/stl-algorithms" },
            { title: "Sorting Algorithms", slug: "dsa-cpp/sorting-algorithms" },
            { title: "Classic Algorithms", slug: "dsa-cpp/classic-algorithms" },
            { title: "Problem Solving", slug: "dsa-cpp/problem-solving" },
        ],
    },
    {
        title: "Monorepo",
        items: [
            { title: "Getting Started", slug: "monorepo/getting-started" },
            { title: "Turborepo", slug: "monorepo/turborepo" },
        ],
    },
    {
        title: "React",
        items: [
            { title: "How React Works", slug: "react/how-react-works" },
            { title: "Props & Event Handlers", slug: "react/props-and-events" },
            { title: "State", slug: "react/state" },
            { title: "Side Effects", slug: "react/side-effects" },
            { title: "Hooks", slug: "react/hooks" },
            { title: "Context & State Management", slug: "react/context-and-state" },
            { title: "Routing", slug: "react/routing" },
            { title: "Browser APIs", slug: "react/browser-apis" },
        ],
    },
    {
        title: "Next.js",
        items: [
            { title: "Getting Started", slug: "nextjs/getting-started" },
            { title: "Rendering Strategies", slug: "nextjs/rendering" },
            { title: "Server & Client Components", slug: "nextjs/server-and-client-components" },
            { title: "API Routes", slug: "nextjs/api-routes" },
            { title: "Hydration", slug: "nextjs/hydration" },
            { title: "React Hook Form", slug: "nextjs/react-hook-form" },
            { title: "Server Actions & Forms", slug: "nextjs/server-actions-forms" },
        ],
    },
    {
        title: "Node.js",
        items: [
            { title: "ES Modules", slug: "nodejs/es-modules" },
            { title: "Cookie Authentication", slug: "nodejs/cookie-authentication" },
            { title: "Token Authentication", slug: "nodejs/token-authentication" },
            { title: "Full-Stack Authentication", slug: "nodejs/authentication-full-stack" },
            { title: "Async Generators & Yield", slug: "nodejs/async-generators" },
            { title: "Buffers", slug: "nodejs/buffers" },
            { title: "Streams", slug: "nodejs/streams" },
            { title: "File System", slug: "nodejs/file-system" },
            { title: "Paths", slug: "nodejs/paths" },
            { title: "CLI Tools", slug: "nodejs/cli-tools" },
        ],
    },
    {
        title: "Express.js",
        items: [
            { title: "Express API", slug: "expressjs/express-api" },
            { title: "Express Middleware", slug: "expressjs/express-middleware" },
            { title: "Express Server", slug: "expressjs/express-server" },
            { title: "Express Request", slug: "expressjs/express-request" },
            { title: "Express Request Reference", slug: "expressjs/express-request-ref" },
            { title: "Express Response Reference", slug: "expressjs/express-response-ref" },
            { title: "Express Router", slug: "expressjs/express-router" },
        ],
    },
    {
        title: "Random",
        items: [
            { title: "AbortController", slug: "random/abort-controller" },
            { title: "Linux Commands", slug: "random/linux-commands" },
            { title: "Shell Fundamentals", slug: "random/shell-fundamentals" },
            { title: "Shell Scripting", slug: "random/shell-scripting" },
            { title: "Standard Streams", slug: "random/standard-streams" },
            { title: "Text Processing", slug: "random/text-processing" },
            { title: "Environment and Config", slug: "random/environment-and-config" },
            { title: "File Permissions", slug: "random/file-permissions" },
            { title: "Filesystem", slug: "random/filesystem" },
            { title: "Processes", slug: "random/processes" },
            { title: "HTTP and Networking", slug: "random/http-and-networking" },
            { title: "SSH", slug: "random/ssh" },
            { title: "tsconfig.json", slug: "random/tsconfig" },
            { title: "WebSockets", slug: "random/websockets" },
            { title: "WebSockets in Production", slug: "random/websockets-production" },
        ],
    },
    {
        title: "GenAI",
        items: [
            { title: "Transformer Fundamentals", slug: "genai-python/transformer-fundamentals" },
            { title: "Python Environment", slug: "genai-python/python-environment" },
            { title: "Prompting", slug: "genai-python/prompting" },
            { title: "Inference", slug: "genai-python/inference" },
            { title: "Fine-Tuning", slug: "genai-python/fine-tuning" },
            { title: "RAG Fundamentals", slug: "genai-python/rag-fundamentals" },
            { title: "Advanced RAG", slug: "genai-python/rag-advanced" },
            { title: "LangChain", slug: "genai-python/langchain" },
            { title: "LangGraph", slug: "genai-python/langgraph" },
            { title: "Knowledge Graphs & Memory", slug: "genai-python/knowledge-graphs-memory" },
            { title: "Tracing", slug: "genai-python/tracing" },
            { title: "MCP, A2A & Guardrails", slug: "genai-python/mcp-a2a-guardrails" },
        ],
    },
    {
        title: "System Design",
        items: [
            { title: "Rate Limiting Fundamentals", slug: "system-design/rate-limiting-fundamentals" },
            { title: "Rate Limiting Implementation", slug: "system-design/rate-limiting-implementation" },
            { title: "Rate Limiting Technologies", slug: "system-design/rate-limiting-technologies" },
            { title: "Rate Limiting Practical (Local)", slug: "system-design/rate-limiting-practical-local" },
            { title: "Rate Limiting Practical (Distributed)", slug: "system-design/rate-limiting-practical-distributed" },
            { title: "Caching Fundamentals", slug: "system-design/caching-fundamentals" },
            { title: "Caching Strategies", slug: "system-design/caching-strategies" },
            { title: "Caching Technologies", slug: "system-design/caching-technologies" },
            { title: "Caching Practical (Strategies)", slug: "system-design/caching-practical-strategies" },
            { title: "Caching Practical (Redis)", slug: "system-design/caching-practical-redis" },
            { title: "Load Balancing Fundamentals", slug: "system-design/load-balancing-fundamentals" },
            { title: "Load Balancing Algorithms", slug: "system-design/load-balancing-algorithms" },
            { title: "Load Balancing Technologies", slug: "system-design/load-balancing-technologies" },
            { title: "Load Balancing Practical (NGINX)", slug: "system-design/load-balancing-practical-nginx" },
            { title: "Load Balancing Practical (Custom)", slug: "system-design/load-balancing-practical-custom" },
        ],
    },
];